name: en685662
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - fuzzywuzzy
  - joblib
  - requests
  - pip:
      - streamlit